development:
  domain: localhost:3000
  client_name: <%= @client_name %>

test:
  domain: test.host
  client_name: <%= @client_name %>

production:
  domain: <%= @app_name %>.taylored-software.com
  client_name: <%= @client_name %>
